#ifndef COMMONENUM_H
#define COMMONENUM_H
enum Direction{LEFT_TURNING,THROUGH,RIGHT_TURNING};
enum region{REGION_E_W,REGION_N_S,REGION_W_E,REGION_S_N};
enum GENMETHOD{GEN_3,GEN_5};
#endif // COMMONENUM_H
